redis:
  host: '127.0.0.1'
  port: 6379
  password: '123456'
  db: 4

postgresql:
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'fastapi'

app:
  host: '127.0.0.1'
  port: 9527
